---
apiVersion: v1
kind: Service
metadata:
  name: challenge-api-svc
  namespace: pricing
spec:
  selector:
    app: challenge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP